spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homiko-prod
    username: homiko
    password: homiko123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public

logging:
  level:
    liquibase: INFO
