spring:
  application:
    name: homiko
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  servlet:
    context-path: /
